'use strict';
// Resource: http://giphy.com/categories
// There are 1264 answers

// Setup
let Answer = require('../models/answer.js');
let mongoose = require('mongoose');


// Connecting to Mongo DB
mongoose.connect('mongodb://localhost/giphy', (error) => {
	if (error) {
		console.log('Cannot connect to db. Error: ', err);
	} else {
		console.log('Connected to database.');
	}
});

// List of search terms (objects in an array)
let answerObject = [

// Actions
{id: 0, text: 'breaking up'},
{id: 0, text: 'cooking'},
{id: 0, text: 'crying'},
{id: 0, text: 'dancing'},
{id: 0, text: 'dreaming'},
{id: 0, text: 'drinking'},
{id: 0, text: 'eating'},
{id: 0, text: 'fainting'},
{id: 0, text: 'falling'},
{id: 0, text: 'fighting'},
{id: 0, text: 'finger guns'},
{id: 0, text: 'flirting'},
{id: 0, text: 'laughing'},
{id: 0, text: 'pout'},
{id: 0, text: 'running'},
{id: 0, text: 'singing'},
{id: 0, text: 'slapping'},
{id: 0, text: 'sleeping'},
{id: 0, text: 'smiling'},
{id: 0, text: 'smoking'},
{id: 0, text: 'sneezing'},
{id: 0, text: 'spinning'},
{id: 0, text: 'swimming'},
{id: 0, text: 'tossing drink'},
{id: 0, text: 'waiting'},
{id: 0, text: 'middle finger'},

// Adjectives
{id: 0, text: 'black and white'},
{id: 0, text: 'bright'},
{id: 0, text: 'cold'},
{id: 0, text: 'creepy'},
{id: 0, text: 'cute'},
{id: 0, text: 'dark'},
{id: 0, text: 'funny'},
{id: 0, text: 'hd'},
{id: 0, text: 'hot'},
{id: 0, text: 'pretty'},
{id: 0, text: 'scary'},
{id: 0, text: 'sexy'},
{id: 0, text: 'slow motion'},
{id: 0, text: 'trippy'},
{id: 0, text: 'vintage'},
{id: 0, text: 'weird'},

// Animals
{id: 0, text: 'badger'},
{id: 0, text: 'bat'},
{id: 0, text: 'bear'},
{id: 0, text: 'bird'},
{id: 0, text: 'bulldog'},
{id: 0, text: 'butterfly'},
{id: 0, text: 'camel'},
{id: 0, text: 'cat'},
{id: 0, text: 'caterpillar'},
{id: 0, text: 'chicken'},
{id: 0, text: 'chihuahua'},
{id: 0, text: 'corgi'},
{id: 0, text: 'cow'},
{id: 0, text: 'crab'},
{id: 0, text: 'deer'},
{id: 0, text: 'dog'},
{id: 0, text: 'dragon'},
{id: 0, text: 'duck'},
{id: 0, text: 'eagle'},
{id: 0, text: 'echidna'},
{id: 0, text: 'elephant'},
{id: 0, text: 'ferret'},
{id: 0, text: 'fish'},
{id: 0, text: 'fox'},
{id: 0, text: 'frog'},
{id: 0, text: 'giraffe'},
{id: 0, text: 'goat'},
{id: 0, text: 'grumpy cat'},
{id: 0, text: 'hamster'},
{id: 0, text: 'hedgehog'},
{id: 0, text: 'hippo'},
{id: 0, text: 'horse'},
{id: 0, text: 'insect'},
{id: 0, text: 'jellyfish'},
{id: 0, text: 'kangaroo'},
{id: 0, text: 'koala'},
{id: 0, text: 'lion'},
{id: 0, text: 'lizard'},
{id: 0, text: 'lobster'},
{id: 0, text: 'maru'},
{id: 0, text: 'monkey'},
{id: 0, text: 'mouse'},
{id: 0, text: 'octopus'},
{id: 0, text: 'otter'},
{id: 0, text: 'owl'},
{id: 0, text: 'panda'},
{id: 0, text: 'penguin'},
{id: 0, text: 'pig'},
{id: 0, text: 'polar bear'},
{id: 0, text: 'poodle'},
{id: 0, text: 'porcupine'},
{id: 0, text: 'praying mantis'},
{id: 0, text: 'pug'},
{id: 0, text: 'rabbit'},
{id: 0, text: 'raccoon'},
{id: 0, text: 'red panda'},
{id: 0, text: 'shark'},
{id: 0, text: 'sheep'},
{id: 0, text: 'skunk'},
{id: 0, text: 'sloth'},
{id: 0, text: 'snake'},
{id: 0, text: 'spider'},
{id: 0, text: 'squirrel'},
{id: 0, text: 'starfish'},
{id: 0, text: 'tiger'},
{id: 0, text: 'turtle'},
{id: 0, text: 'unicorn'},
{id: 0, text: 'whale'},
{id: 0, text: 'wolf'},

// Anime
{id: 0, text: 'berserk'},
{id: 0, text: 'black lagoon'},
{id: 0, text: 'bleach'},
{id: 0, text: 'cardcaptor sakura'},
{id: 0, text: 'code geass'},
{id: 0, text: 'cowboy bebop'},
{id: 0, text: 'death note'},
{id: 0, text: 'evangelion'},
{id: 0, text: 'flcl'},
{id: 0, text: 'fullmetal alchemist'},
{id: 0, text: 'gundam'},
{id: 0, text: 'hamtaro'},
{id: 0, text: 'hayao miyazaki'},
{id: 0, text: 'hetalia'},
{id: 0, text: 'hinata hyuga'},
{id: 0, text: 'inuyasha'},
{id: 0, text: 'kakashi hatake'},
{id: 0, text: 'kawaii'},
{id: 0, text: 'kiba'},
{id: 0, text: 'manga'},
{id: 0, text: 'my neighbor totoro'},
{id: 0, text: 'naruto'},
{id: 0, text: 'ninja scroll'},
{id: 0, text: 'one piece'},
{id: 0, text: 'pokemon'},
{id: 0, text: 'princess mononoke'},
{id: 0, text: 'rock lee'},
{id: 0, text: 'sailor moon'},
{id: 0, text: 'sakura'},
{id: 0, text: 'samurai champloo'},
{id: 0, text: 'spaceship battleship yamato'},
{id: 0, text: 'spirited away'},
{id: 0, text: 'trigun'},

// Art and Design (lame stuff mostly)
{id: 0, text: '3d'},
{id: 0, text: 'animation'},
{id: 0, text: 'architecture'},
{id: 0, text: 'art'},
{id: 0, text: 'black and white'},
{id: 0, text: 'cinemagraph'},
{id: 0, text: 'collage'},
{id: 0, text: 'design'},
{id: 0, text: 'geometry'},
{id: 0, text: 'glitch'},
{id: 0, text: 'illustration'},
{id: 0, text: 'loop'},
{id: 0, text: 'mash up'},
{id: 0, text: 'morph'},
{id: 0, text: 'photography'},
{id: 0, text: 'pixel'},
{id: 0, text: 'psychedelic'},
{id: 0, text: 'sculpture'},
{id: 0, text: 'timelapse'},
{id: 0, text: 'transparent'},
{id: 0, text: 'typography'},

// Cartoons and Comics
{id: 0, text: '101 dalmatians'},
{id: 0, text: 'adult swim'},
{id: 0, text: 'adventure time'},
{id: 0, text: 'aeon flux'},
{id: 0, text: 'aladdin'},
{id: 0, text: 'alice in wonderland'},
{id: 0, text: 'alvin and the chipmunks'},
{id: 0, text: 'animaniacs'},
{id: 0, text: 'aqua teen hunger force'},
{id: 0, text: 'archer'},
{id: 0, text: 'archie comics'},
{id: 0, text: 'arthur'},
{id: 0, text: 'bambi'},
{id: 0, text: 'batman'},
{id: 0, text: 'beauty and the beast'},
{id: 0, text: 'beavis and butthead'},
{id: 0, text: 'betty boop'},
{id: 0, text: 'bobs burgers'},
{id: 0, text: 'calvin and hobbes'},
{id: 0, text: 'captain planet'},
{id: 0, text: 'cars'},
{id: 0, text: 'cartoon network'},
{id: 0, text: 'cyanide and happiness'},
{id: 0, text: 'daffy duck'},
{id: 0, text: 'daria'},
{id: 0, text: 'dexters laboratory'},
{id: 0, text: 'disney'},
{id: 0, text: 'doug'},
{id: 0, text: 'dreamworks'},
{id: 0, text: 'family guy'},
{id: 0, text: 'fantasia'},
{id: 0, text: 'fat albert'},
{id: 0, text: 'finding nemo'},
{id: 0, text: 'fosters home for imaginary friends'},
{id: 0, text: 'futurama'},
{id: 0, text: 'garfield'},
{id: 0, text: 'george of the jungle'},
{id: 0, text: 'gi joe'},
{id: 0, text: 'gravity falls'},
{id: 0, text: 'grinch who stole christmas'},
{id: 0, text: 'gumby'},
{id: 0, text: 'harvey birdman'},
{id: 0, text: 'hey arnold'},
{id: 0, text: 'home movies'},
{id: 0, text: 'homestuck'},
{id: 0, text: 'hotel transylvania'},
{id: 0, text: 'jem and the holograms'},
{id: 0, text: 'johnny bravo'},
{id: 0, text: 'josie and the pussycats'},
{id: 0, text: 'king of the hill'},
{id: 0, text: 'looney tunes'},
{id: 0, text: 'magical game time'},
{id: 0, text: 'metalocaypse'},
{id: 0, text: 'mickey mouse'},
{id: 0, text: 'minnie mouse'},
{id: 0, text: 'mr magoo'},
{id: 0, text: 'mulan'},
{id: 0, text: 'muppet babies'},
{id: 0, text: 'my little pony'},
{id: 0, text: 'peanuts'},
{id: 0, text: 'peter pan'},
{id: 0, text: 'phinas and ferb'},
{id: 0, text: 'pink panther'},
{id: 0, text: 'pinocchio'},
{id: 0, text: 'pocahontas'},
{id: 0, text: 'popeye'},
{id: 0, text: 'porky pig'},
{id: 0, text: 'regular show'},
{id: 0, text: 'ren and stimpy'},
{id: 0, text: 'rockos modern life'},
{id: 0, text: 'rocky and bullwinkle'},
{id: 0, text: 'rugrats'},
{id: 0, text: 'samurai jack'},
{id: 0, text: 'schoolhouse rock'},
{id: 0, text: 'scooby doo'},
{id: 0, text: 'sealab 2021'},
{id: 0, text: 'sleeping beauty'},
{id: 0, text: 'snow white'},
{id: 0, text: 'south park'},
{id: 0, text: 'space ghost'},
{id: 0, text: 'speed racer'},
{id: 0, text: 'spongebob squarepants'},
{id: 0, text: 'tailspin'},
{id: 0, text: 'tangled'},
{id: 0, text: 'teen titans'},
{id: 0, text: 'teenage mutant ninja turtles'},
{id: 0, text: 'the boondocks'},
{id: 0, text: 'the critic'},
{id: 0, text: 'the flintstones'},
{id: 0, text: 'the incredibles'},
{id: 0, text: 'the jetsons'},
{id: 0, text: 'the lion king'},
{id: 0, text: 'the little mermaid'},
{id: 0, text: 'the oatmeal'},
{id: 0, text: 'the powerpuff girls'},
{id: 0, text: 'the simpsons'},
{id: 0, text: 'the venture bros'},
{id: 0, text: 'tom and jerry'},
{id: 0, text: 'top cat'},
{id: 0, text: 'toy story'},
{id: 0, text: 'tweety bird'},
{id: 0, text: 'underdog'},
{id: 0, text: 'voltron'},
{id: 0, text: 'wall e'},
{id: 0, text: 'wile e coyote'},
{id: 0, text: 'winnie the pooh'},
{id: 0, text: 'yogi bear'},

// Celebrities
{id: 0, text: 'adam baldwin'},
{id: 0, text: 'adam brody'},
{id: 0, text: 'adam devine'},
{id: 0, text: 'adam sandler'},
{id: 0, text: 'adam scott'},
{id: 0, text: 'adrien brody'},
{id: 0, text: 'al pacino'},
{id: 0, text: 'alec baldwin'},
{id: 0, text: 'alexa chung'},
{id: 0, text: 'alia shawkat'},
{id: 0, text: 'alison brie'},
{id: 0, text: 'amanda bynes'},
{id: 0, text: 'amy poehler'},
{id: 0, text: 'andrew garfield'},
{id: 0, text: 'angelina jolie'},
{id: 0, text: 'anna kendrick'},
{id: 0, text: 'anne hathaway'},
{id: 0, text: 'arnold schwarzenegger'},
{id: 0, text: 'ashley benson'},
{id: 0, text: 'aubrey plaza'},
{id: 0, text: 'aziz ansari'},
{id: 0, text: 'ben stiller'},
{id: 0, text: 'bill cosby'},
{id: 0, text: 'brad pitt'},
{id: 0, text: 'bradley cooper'},
{id: 0, text: 'bruce lee'},
{id: 0, text: 'bruce willis'},
{id: 0, text: 'bryan cranston'},
{id: 0, text: 'carey mulligan'},
{id: 0, text: 'charlie sheen'},
{id: 0, text: 'chris hemsworth'},
{id: 0, text: 'chris pratt'},
{id: 0, text: 'chris rock'},
{id: 0, text: 'christian bale'},
{id: 0, text: 'chuck norris'},
{id: 0, text: 'cillian murphy'},
{id: 0, text: 'clint eastwood'},
{id: 0, text: 'conan obrien'},
{id: 0, text: 'connie britton'},
{id: 0, text: 'daniel day lewis'},
{id: 0, text: 'danny mcbride'},
{id: 0, text: 'dave chappelle'},
{id: 0, text: 'dave franco'},
{id: 0, text: 'david cross'},
{id: 0, text: 'david duchovny'},
{id: 0, text: 'denzel washington'},
{id: 0, text: 'dolph lundgren'},
{id: 0, text: 'don cheadle'},
{id: 0, text: 'donald glover'},
{id: 0, text: 'ed helms'},
{id: 0, text: 'eddie izzard'},
{id: 0, text: 'eddie murphy'},
{id: 0, text: 'elijah wood'},
{id: 0, text: 'elizabeth banks'},
{id: 0, text: 'ellen page'},
{id: 0, text: 'emily blunt'},
{id: 0, text: 'emma roberts'},
{id: 0, text: 'emma stone'},
{id: 0, text: 'emma watson'},
{id: 0, text: 'eva green'},
{id: 0, text: 'gary oldman'},
{id: 0, text: 'george carlin'},
{id: 0, text: 'harrison ford'},
{id: 0, text: 'hayden panettiere'},
{id: 0, text: 'heath ledger'},
{id: 0, text: 'heather graham'},
{id: 0, text: 'ian somerhalder'},
{id: 0, text: 'jack mcbrayer'},
{id: 0, text: 'jackie chan'},
{id: 0, text: 'jake gyllenhaal'},
{id: 0, text: 'james franco'},
{id: 0, text: 'jason bateman'},
{id: 0, text: 'jason schwartzman'},
{id: 0, text: 'javier bardem'},
{id: 0, text: 'jay baruchel'},
{id: 0, text: 'jean claude van damme'},
{id: 0, text: 'jeffrey tambor'},
{id: 0, text: 'jennifer lawrence'},
{id: 0, text: 'jeremy renner'},
{id: 0, text: 'jessica walter'},
{id: 0, text: 'jet li'},
{id: 0, text: 'jim carrey'},
{id: 0, text: 'jim gaffigan'},
{id: 0, text: 'john cusack'},
{id: 0, text: 'john hodgman'},
{id: 0, text: 'john travolta'},
{id: 0, text: 'johnny depp'},
{id: 0, text: 'jon hamm'},
{id: 0, text: 'jon stewart'},
{id: 0, text: 'jonah hill'},
{id: 0, text: 'joseph gordon levitt'},
{id: 0, text: 'jude law'},
{id: 0, text: 'julianne moore'},
{id: 0, text: 'karen gillan'},
{id: 0, text: 'kate upton'},
{id: 0, text: 'keira knightley'},
{id: 0, text: 'ken jeong'},
{id: 0, text: 'kristen wiig'},
{id: 0, text: 'kyle chandler'},
{id: 0, text: 'larry david'},
{id: 0, text: 'leonardo dicaprio'},
{id: 0, text: 'liam neeson'},
{id: 0, text: 'louis ck'},
{id: 0, text: 'macaulay culkin'},
{id: 0, text: 'mark ruffalo'},
{id: 0, text: 'matt lucas'},
{id: 0, text: 'matt smith'},
{id: 0, text: 'matthew goode'},
{id: 0, text: 'matthew perry'},
{id: 0, text: 'maya rudolph'},
{id: 0, text: 'megan fox'},
{id: 0, text: 'melissa mccarthy'},
{id: 0, text: 'mia wasikowska'},
{id: 0, text: 'michael caine'},
{id: 0, text: 'michael cera'},
{id: 0, text: 'michael fassbender'},
{id: 0, text: 'michael ian black'},
{id: 0, text: 'mickey rourke'},
{id: 0, text: 'mike tyson'},
{id: 0, text: 'mila kunis'},
{id: 0, text: 'mindy kaling'},
{id: 0, text: 'minka kelly'},
{id: 0, text: 'mischa barton'},
{id: 0, text: 'morgan freeman'},
{id: 0, text: 'mr. t'},
{id: 0, text: 'natalie portman'},
{id: 0, text: 'nick offerman'},
{id: 0, text: 'nicolas cage'},
{id: 0, text: 'olivia munn'},
{id: 0, text: 'olivia wilde'},
{id: 0, text: 'orlando bloom'},
{id: 0, text: 'patton oswalt'},
{id: 0, text: 'paul dano'},
{id: 0, text: 'paul rudd'},
{id: 0, text: 'paul scheer'},
{id: 0, text: 'peter gallagher'},
{id: 0, text: 'portia de rossi'},
{id: 0, text: 'rachel bilson'},
{id: 0, text: 'rachel leigh cook'},
{id: 0, text: 'rachel mccadams'},
{id: 0, text: 'rachel weisz'},
{id: 0, text: 'rebel wilson'},
{id: 0, text: 'richard pryor'},
{id: 0, text: 'ricky gervais'},
{id: 0, text: 'rob huebel'},
{id: 0, text: 'rob lowe'},
{id: 0, text: 'robert de niro'},
{id: 0, text: 'robert downey jr'},
{id: 0, text: 'robert redford'},
{id: 0, text: 'rooney mara'},
{id: 0, text: 'ru paul'},
{id: 0, text: 'ryan gosling'},
{id: 0, text: 'sam rockwell'},
{id: 0, text: 'samuel l jackson'},
{id: 0, text: 'scarlett johansson'},
{id: 0, text: 'sean connery'},
{id: 0, text: 'seth green'},
{id: 0, text: 'seth rogen'},
{id: 0, text: 'stephen colbert'},
{id: 0, text: 'steve carell'},
{id: 0, text: 'sylvester stallone'},
{id: 0, text: 'taylor kitsch'},
{id: 0, text: 'tina fey'},
{id: 0, text: 'tobey maguire'},
{id: 0, text: 'tom cruise'},
{id: 0, text: 'tom hanks'},
{id: 0, text: 'tom hardy'},
{id: 0, text: 'tom hiddleston'},
{id: 0, text: 'tony hale'},
{id: 0, text: 'topher grace'},
{id: 0, text: 'tracy morgan'},
{id: 0, text: 'vanessa hudgens'},
{id: 0, text: 'weird al yankovic'},
{id: 0, text: 'will arnett'},
{id: 0, text: 'will ferrell'},
{id: 0, text: 'will forte'},
{id: 0, text: 'will smith'},
{id: 0, text: 'willem dafoe'},
{id: 0, text: 'yvonne strahovski'},
{id: 0, text: 'zach galifianakis'},
{id: 0, text: 'zachary levi'},
{id: 0, text: 'zachary quinto'},
{id: 0, text: 'zooey deschanel'},

// Decades
{id: 0, text: '20s'},
{id: 0, text: '30s'},
{id: 0, text: '40s'},
{id: 0, text: '50s'},
{id: 0, text: '60s'},
{id: 0, text: '70s'},
{id: 0, text: '80s'},
{id: 0, text: '90s'},
{id: 0, text: 'vintage'},

// Election 2016
{id: 0, text: 'ben carson'},
{id: 0, text: 'bernie sanders'},
{id: 0, text: 'carly fiorina'},
{id: 0, text: 'chris christie'},
{id: 0, text: 'donald trump'},
{id: 0, text: 'hillary clinton'},
{id: 0, text: 'jeb bush'},
{id: 0, text: 'joe biden'},
{id: 0, text: 'marco rubio'},
{id: 0, text: 'america'},
{id: 0, text: 'democrat'},
{id: 0, text: 'economy'},
{id: 0, text: 'gop'},
{id: 0, text: 'jim webb'},
{id: 0, text: 'lawrence lessig'},
{id: 0, text: 'politics'},
{id: 0, text: 'president'},
{id: 0, text: 'rand paul'},
{id: 0, text: 'usa'},

// Emotions
{id: 0, text: 'angry'},
{id: 0, text: 'bored'},
{id: 0, text: 'disappointed'},
{id: 0, text: 'drunk'},
{id: 0, text: 'embarassed'},
{id: 0, text: 'excited'},
{id: 0, text: 'frustrated'},
{id: 0, text: 'happy'},
{id: 0, text: 'hungry'},
{id: 0, text: 'inspired'},
{id: 0, text: 'lonely'},
{id: 0, text: 'love'},
{id: 0, text: 'nervous'},
{id: 0, text: 'pain'},
{id: 0, text: 'reaction'},
{id: 0, text: 'relaxed'},
{id: 0, text: 'sad'},
{id: 0, text: 'sassy'},
{id: 0, text: 'scared'},
{id: 0, text: 'shocked'},
{id: 0, text: 'sick'},
{id: 0, text: 'stressed'},
{id: 0, text: 'surprised'},
{id: 0, text: 'suspicious'},
{id: 0, text: 'tired'},
{id: 0, text: 'unimpressed'},
{id: 0, text: 'awkward'},
{id: 0, text: 'confused'},
{id: 0, text: 'mind blown'},

// Fasion and beauty (lame; not funny; not doing this one)

// Food and Drink
{id: 0, text: 'alcohol'},
{id: 0, text: 'apple'},
{id: 0, text: 'bacon'},
{id: 0, text: 'banana'},
{id: 0, text: 'beer'},
{id: 0, text: 'bread'},
{id: 0, text: 'broccoli'},
{id: 0, text: 'brownies'},
{id: 0, text: 'burrito'},
{id: 0, text: 'cake'},
{id: 0, text: 'cheese'},
{id: 0, text: 'cheeseburger'},
{id: 0, text: 'coffee'},
{id: 0, text: 'cookie'},
{id: 0, text: 'doughnut'},
{id: 0, text: 'egg roll'},
{id: 0, text: 'french fries'},
{id: 0, text: 'french toast'},
{id: 0, text: 'ham'},
{id: 0, text: 'hot dog'},
{id: 0, text: 'ice cream'},
{id: 0, text: 'orange fruit'},
{id: 0, text: 'pancakes'},
{id: 0, text: 'pasta'},
{id: 0, text: 'pickle'},
{id: 0, text: 'pie'},
{id: 0, text: 'pizza'},
{id: 0, text: 'salad'},
{id: 0, text: 'sandwich'},
{id: 0, text: 'soda'},
{id: 0, text: 'steak'},
{id: 0, text: 'sushi'},
{id: 0, text: 'taco'},
{id: 0, text: 'tea'},
{id: 0, text: 'vodka'},
{id: 0, text: 'whiskey'},
{id: 0, text: 'breakfast'},
{id: 0, text: 'doughnut'},

// Gaming
{id: 0, text: '8bit'},
{id: 0, text: 'animal crossing'},
{id: 0, text: 'atari'},
{id: 0, text: 'bioshock'},
{id: 0, text: 'call of duty'},
{id: 0, text: 'dead space'},
{id: 0, text: 'donkey kong'},
{id: 0, text: 'duck hunt'},
{id: 0, text: 'earthbound'},
{id: 0, text: 'final fantasy'},
{id: 0, text: 'galaga'},
{id: 0, text: 'game boy'},
{id: 0, text: 'gears of war'},
{id: 0, text: 'grand theft auto'},
{id: 0, text: 'half life'},
{id: 0, text: 'kirby'},
{id: 0, text: 'mario kart'},
{id: 0, text: 'max payne'},
{id: 0, text: 'metal gear solid'},
{id: 0, text: 'metroid'},
{id: 0, text: 'mods'},
{id: 0, text: 'mortal kombat'},
{id: 0, text: 'n64'},
{id: 0, text: 'nes'},
{id: 0, text: 'nintendo'},
{id: 0, text: 'pacman'},
{id: 0, text: 'portal'},
{id: 0, text: 'prince of persia'},
{id: 0, text: 'sega'},
{id: 0, text: 'skyrim'},
{id: 0, text: 'sonic the hedgehog'},
{id: 0, text: 'sprites'},
{id: 0, text: 'starcraft'},
{id: 0, text: 'starfox'},
{id: 0, text: 'street fighter'},
{id: 0, text: 'streets of rage'},
{id: 0, text: 'super mario'},
{id: 0, text: 'super nintendo'},
{id: 0, text: 'super smash bros'},
{id: 0, text: 'tetris'},
{id: 0, text: 'the last of us'},
{id: 0, text: 'the legend of zelda'},
{id: 0, text: 'the sims'},
{id: 0, text: 'tomb raider'},
{id: 0, text: 'video game physics'},
{id: 0, text: 'wolfenstein 3d'},
{id: 0, text: 'world of warcraft'},
{id: 0, text: 'bioshock infinite'},

// Holidays
{id: 0, text: 'april fools day'},
{id: 0, text: 'birthday'},
{id: 0, text: 'christmas'},
{id: 0, text: 'cinco de mayo'},
{id: 0, text: 'easter'},
{id: 0, text: 'fathers day'},
{id: 0, text: 'fourth of july'},
{id: 0, text: 'graduation'},
{id: 0, text: 'halloween'},
{id: 0, text: 'hanukkah'},
{id: 0, text: 'kwanzaa'},
{id: 0, text: 'mardi gras'},
{id: 0, text: 'memorial day'},
{id: 0, text: 'mothers day'},
{id: 0, text: 'new years'},
{id: 0, text: 'oktoberfest'},
{id: 0, text: 'st patricks day'},
{id: 0, text: 'thanksgiving'},
{id: 0, text: 'valentines day'},
{id: 0, text: 'wedding'},

// Interests
{id: 0, text: 'alien'},
{id: 0, text: 'autumn'},
{id: 0, text: 'baby'},
{id: 0, text: 'ballet'},
{id: 0, text: 'boobs'},
{id: 0, text: 'boy'},
{id: 0, text: 'butt'},
{id: 0, text: 'clown'},
{id: 0, text: 'ghost'},
{id: 0, text: 'girl'},
{id: 0, text: 'internet'},
{id: 0, text: 'iphone'},
{id: 0, text: 'lgbt'},
{id: 0, text: 'new york city'},
{id: 0, text: 'party'},
{id: 0, text: 'robot'},
{id: 0, text: 'roller coaster'},
{id: 0, text: 'spring'},
{id: 0, text: 'summer'},
{id: 0, text: 'theme park'},
{id: 0, text: 'tumblr'},
{id: 0, text: 'vacation'},
{id: 0, text: 'vampire'},
{id: 0, text: 'winter'},
{id: 0, text: 'work'},
{id: 0, text: 'zombie'},

// Memes
{id: 0, text: 'bitch im fabulous'},
{id: 0, text: 'come at me bro'},
{id: 0, text: 'dat ass'},
{id: 0, text: 'fail'},
{id: 0, text: 'fangirling'},
{id: 0, text: 'feels'},
{id: 0, text: 'forever alone'},
{id: 0, text: 'let me love you'},
{id: 0, text: 'like a boss'},
{id: 0, text: 'look at all the fucks i give'},
{id: 0, text: 'nyan cat'},
{id: 0, text: 'rickroll'},
{id: 0, text: 'spinning lana'},
{id: 0, text: 'steal yo girl'},
{id: 0, text: 'sturgeon face'},
{id: 0, text: 'surprised patrick'},
{id: 0, text: 'swag'},
{id: 0, text: 'troll'},
{id: 0, text: 'win'},
{id: 0, text: 'deal with it'},
{id: 0, text: 'party hard'},

// Movies
{id: 0, text: '21 jump street'},
{id: 0, text: '28 days later'},
{id: 0, text: '500 days of summer'},
{id: 0, text: 'ace ventura'},
{id: 0, text: 'addams family'},
{id: 0, text: 'alfred hitchcock'},
{id: 0, text: 'amelie'},
{id: 0, text: 'american psycho'},
{id: 0, text: 'anchorman'},
{id: 0, text: 'annie hall'},
{id: 0, text: 'apocalypse now'},
{id: 0, text: 'battle royale'},
{id: 0, text: 'beetlejuice'},
{id: 0, text: 'big fish'},
{id: 0, text: 'black swan'},
{id: 0, text: 'bladerunner'},
{id: 0, text: 'blue velvet'},
{id: 0, text: 'boondock saints'},
{id: 0, text: 'braveheart'},
{id: 0, text: 'breakfast at tiffanys'},
{id: 0, text: 'breathless'},
{id: 0, text: 'bridesmaids'},
{id: 0, text: 'casablanca'},
{id: 0, text: 'casino'},
{id: 0, text: 'chinatown'},
{id: 0, text: 'citizen kane'},
{id: 0, text: 'clueless'},
{id: 0, text: 'cry baby'},
{id: 0, text: 'david lynch'},
{id: 0, text: 'deliverance'},
{id: 0, text: 'dirty harry'},
{id: 0, text: 'django unchained'},
{id: 0, text: 'doctor strangelove'},
{id: 0, text: 'dodgeball'},
{id: 0, text: 'donnie darko'},
{id: 0, text: 'easy rider'},
{id: 0, text: 'edward scissorhands'},
{id: 0, text: 'elf'},
{id: 0, text: 'encino man'},
{id: 0, text: 'eraserhead'},
{id: 0, text: 'escape from new york'},
{id: 0, text: 'eternal sunshine of the spotless mind'},
{id: 0, text: 'evil dead'},
{id: 0, text: 'fellini'},
{id: 0, text: 'fight club'},
{id: 0, text: 'fire walk with me'},
{id: 0, text: 'forrest gump'},
{id: 0, text: 'ghostbusters'},
{id: 0, text: 'gladiator'},
{id: 0, text: 'gone with the wind'},
{id: 0, text: 'goodfellas'},
{id: 0, text: 'harry potter'},
{id: 0, text: 'heathers'},
{id: 0, text: 'high school musical'},
{id: 0, text: 'hocus pocus'},
{id: 0, text: 'horror'},
{id: 0, text: 'inception'},
{id: 0, text: 'indiana jones'},
{id: 0, text: 'iron man'},
{id: 0, text: 'kill bill'},
{id: 0, text: 'kung fu'},
{id: 0, text: 'labyrinth'},
{id: 0, text: 'life of brian'},
{id: 0, text: 'looper'},
{id: 0, text: 'lost boys'},
{id: 0, text: 'marie antoinette'},
{id: 0, text: 'martin scorsese'},
{id: 0, text: 'melancholia'},
{id: 0, text: 'mulholland drive'},
{id: 0, text: 'night of the living dead'},
{id: 0, text: 'pirates of the carribean'},
{id: 0, text: 'pretty in pink'},
{id: 0, text: 'pulp fiction'},
{id: 0, text: 'quentin tarantino'},
{id: 0, text: 'rad'},
{id: 0, text: 'rambo'},
{id: 0, text: 'real genius'},
{id: 0, text: 'reservoir dogs'},
{id: 0, text: 'risky business'},
{id: 0, text: 'rocky'},
{id: 0, text: 'romeo and juliet'},
{id: 0, text: 'rosemarys baby'},
{id: 0, text: 'say anything'},
{id: 0, text: 'scarface'},
{id: 0, text: 'shaun of the dead'},
{id: 0, text: 'shawshank redemption'},
{id: 0, text: 'sin city'},
{id: 0, text: 'sixteen candles'},
{id: 0, text: 'some like it hot'},
{id: 0, text: 'spring breakers'},
{id: 0, text: 'stanley kubrick'},
{id: 0, text: 'star wars'},
{id: 0, text: 'stephen king'},
{id: 0, text: 'submarine'},
{id: 0, text: 'taxi driver'},
{id: 0, text: 'terminator'},
{id: 0, text: 'texas chainsaw massacre'},
{id: 0, text: 'the big lebowski'},
{id: 0, text: 'the bling ring'},
{id: 0, text: 'the blues brothers'},
{id: 0, text: 'the breakfast club'},
{id: 0, text: 'the dark crystal'},
{id: 0, text: 'the dark knight'},
{id: 0, text: 'the diving bell and the butterfly'},
{id: 0, text: 'the fifth element'},
{id: 0, text: 'the godfather'},
{id: 0, text: 'the goonies'},
{id: 0, text: 'the hangover'},
{id: 0, text: 'the lord of the rings'},
{id: 0, text: 'the maltese falcon'},
{id: 0, text: 'the matrix'},
{id: 0, text: 'the muppets'},
{id: 0, text: 'the princess bride'},
{id: 0, text: 'the science of sleep'},
{id: 0, text: 'the shawshank redemption'},
{id: 0, text: 'the shining'},
{id: 0, text: 'the virgin suicides'},
{id: 0, text: 'tim burton'},
{id: 0, text: 'top gun'},
{id: 0, text: 'transformers'},
{id: 0, text: 'tron'},
{id: 0, text: 'twilight'},
{id: 0, text: 'warriors'},
{id: 0, text: 'watchmen'},
{id: 0, text: 'waynes world'},
{id: 0, text: 'weird science'},
{id: 0, text: 'wes anderson'},
{id: 0, text: 'wet hot american summer'},
{id: 0, text: 'willy wonka and the chocolate factory'},
{id: 0, text: 'zombieland'},
{id: 0, text: 'zoolander'},

// Music
{id: 0, text: '50 cent'},
{id: 0, text: 'action bronson'},
{id: 0, text: 'adam lambert'},
{id: 0, text: 'adam levine'},
{id: 0, text: 'adele'},
{id: 0, text: 'alicia keys'},
{id: 0, text: 'anamanaguchi'},
{id: 0, text: 'asap rocky'},
{id: 0, text: 'avril lavigne'},
{id: 0, text: 'backstreet boys'},
{id: 0, text: 'beastie boys'},
{id: 0, text: 'beyonce'},
{id: 0, text: 'big bang'},
{id: 0, text: 'big sean'},
{id: 0, text: 'black eyed peas'},
{id: 0, text: 'bob dylan'},
{id: 0, text: 'bob marley'},
{id: 0, text: 'britney spears'},
{id: 0, text: 'bruno mars'},
{id: 0, text: 'carrie underwood'},
{id: 0, text: 'cassie'},
{id: 0, text: 'childish gambino'},
{id: 0, text: 'chris brown'},
{id: 0, text: 'christina aguilera'},
{id: 0, text: 'cody simpson'},
{id: 0, text: 'coldplay'},
{id: 0, text: 'daft punk'},
{id: 0, text: 'danny brown'},
{id: 0, text: 'david bowie'},
{id: 0, text: 'david guetta'},
{id: 0, text: 'demi lovato'},
{id: 0, text: 'destinys child'},
{id: 0, text: 'drake'},
{id: 0, text: 'elvis presley'},
{id: 0, text: 'eminem'},
{id: 0, text: 'enrique iglesias'},
{id: 0, text: 'frank ocean'},
{id: 0, text: 'g dragon'},
{id: 0, text: 'harry styles'},
{id: 0, text: 'janet jackson'},
{id: 0, text: 'jay z'},
{id: 0, text: 'jennifer lopez'},
{id: 0, text: 'john mayer'},
{id: 0, text: 'johnny cash'},
{id: 0, text: 'justin bieber'},
{id: 0, text: 'justin timberlake'},
{id: 0, text: 'kanye west'},
{id: 0, text: 'katy perry'},
{id: 0, text: 'kelly rowland'},
{id: 0, text: 'kendrick lamar'},
{id: 0, text: 'kesha'},
{id: 0, text: 'kpop'},
{id: 0, text: 'kreayshawn'},
{id: 0, text: 'lady gaga'},
{id: 0, text: 'lana del rey'},
{id: 0, text: 'liam payne'},
{id: 0, text: 'lil wayne'},
{id: 0, text: 'linkin park'},
{id: 0, text: 'louis tomlinson'},
{id: 0, text: 'mac miller'},
{id: 0, text: 'madonna'},
{id: 0, text: 'mariah carey'},
{id: 0, text: 'mc hammer'},
{id: 0, text: 'michael jackson'},
{id: 0, text: 'miley cyrus'},
{id: 0, text: 'morrissey'},
{id: 0, text: 'my chemical romance'},
{id: 0, text: 'niall horan'},
{id: 0, text: 'nicki minaj'},
{id: 0, text: 'nirvana'},
{id: 0, text: 'odd future'},
{id: 0, text: 'one direction'},
{id: 0, text: 'outkast'},
{id: 0, text: 'paramore'},
{id: 0, text: 'pierce the veil'},
{id: 0, text: 'r kelly'},
{id: 0, text: 'rihanna'},
{id: 0, text: 'selena gomez'},
{id: 0, text: 'shakira'},
{id: 0, text: 'skrillex'},
{id: 0, text: 'snoop dogg'},
{id: 0, text: 'solange'},
{id: 0, text: 'taylor swift'},
{id: 0, text: 'tegan and sara'},
{id: 0, text: 'the beatles'},
{id: 0, text: 'the flaming lips'},
{id: 0, text: 'the lonely island'},
{id: 0, text: 'the rolling stones'},
{id: 0, text: 'the strokes'},
{id: 0, text: 'the white stripes'},
{id: 0, text: 'ti'},
{id: 0, text: 'tlc'},
{id: 0, text: 'tyler the creator'},
{id: 0, text: 'usher'},
{id: 0, text: 'vampire weekend'},
{id: 0, text: 'wavves'},
{id: 0, text: 'whitney houston'},
{id: 0, text: 'wiz khalifa'},
{id: 0, text: 'zayn malik'},

// Nature (might be lame)
{id: 0, text: 'beach'},
{id: 0, text: 'cave'},
{id: 0, text: 'clouds'},
{id: 0, text: 'comet'},
{id: 0, text: 'constellations'},
{id: 0, text: 'coral'},
{id: 0, text: 'crystals'},
{id: 0, text: 'desert'},
{id: 0, text: 'fire'},
{id: 0, text: 'forest'},
{id: 0, text: 'geyser'},
{id: 0, text: 'glacier'},
{id: 0, text: 'hurricane'},
{id: 0, text: 'ice'},
{id: 0, text: 'lake'},
{id: 0, text: 'landscape'},
{id: 0, text: 'lava'},
{id: 0, text: 'mist'},
{id: 0, text: 'moon'},
{id: 0, text: 'mountains'},
{id: 0, text: 'mushrooms'},
{id: 0, text: 'night'},
{id: 0, text: 'northern lights'},
{id: 0, text: 'ocean'},
{id: 0, text: 'plants'},
{id: 0, text: 'prairie'},
{id: 0, text: 'rainbow'},
{id: 0, text: 'reef'},
{id: 0, text: 'river'},
{id: 0, text: 'sand'},
{id: 0, text: 'smoke'},
{id: 0, text: 'snow'},
{id: 0, text: 'stars'},
{id: 0, text: 'sun'},
{id: 0, text: 'sunrise'},
{id: 0, text: 'sunset'},
{id: 0, text: 'tornado'},
{id: 0, text: 'trees'},
{id: 0, text: 'tsunami'},
{id: 0, text: 'waterfall'},
{id: 0, text: 'waves'},
{id: 0, text: 'weather'},
{id: 0, text: 'wind'},

// News And Politics
{id: 0, text: 'anthony weiner'},
{id: 0, text: 'barack obama'},
{id: 0, text: 'bill clinton'},
{id: 0, text: 'conclave'},
{id: 0, text: 'congress'},
{id: 0, text: 'conservative'},
{id: 0, text: 'democrat'},
{id: 0, text: 'donald trump'},
{id: 0, text: 'economy'},
{id: 0, text: 'election 2012'},
{id: 0, text: 'hillary clinton'},
{id: 0, text: 'iran'},
{id: 0, text: 'irs'},
{id: 0, text: 'joe biden'},
{id: 0, text: 'john boehner'},
{id: 0, text: 'john mccain'},
{id: 0, text: 'marco rubio'},
{id: 0, text: 'mitch mcconnell'},
{id: 0, text: 'mitt romney'},
{id: 0, text: 'nancy pelosi'},
{id: 0, text: 'north korea'},
{id: 0, text: 'nsa'},
{id: 0, text: 'obamacare'},
{id: 0, text: 'pope'},
{id: 0, text: 'president'},
{id: 0, text: 'protest'},
{id: 0, text: 'republican'},
{id: 0, text: 'ron paul'},
{id: 0, text: 'sarah palin'},
{id: 0, text: 'senate'},
{id: 0, text: 'supreme court'},
{id: 0, text: 'surveillance'},
{id: 0, text: 'syria'},
{id: 0, text: 'tea party'},
{id: 0, text: 'white house'},

// Reactions
{id: 0, text: 'agree'},
{id: 0, text: 'applause'},
{id: 0, text: 'awesome'},
{id: 0, text: 'awww'},
{id: 0, text: 'burn'},
{id: 0, text: 'cool story bro'},
{id: 0, text: 'deal with it'},
{id: 0, text: 'do not want'},
{id: 0, text: 'eww'},
{id: 0, text: 'eye roll'},
{id: 0, text: 'facepalm'},
{id: 0, text: 'finger guns'},
{id: 0, text: 'fist bump'},
{id: 0, text: 'flirt'},
{id: 0, text: 'fml'},
{id: 0, text: 'frown'},
{id: 0, text: 'good luck'},
{id: 0, text: 'goodbye'},
{id: 0, text: 'gtfo'},
{id: 0, text: 'hair flip'},
{id: 0, text: 'happy dance'},
{id: 0, text: 'hearts'},
{id: 0, text: 'hello'},
{id: 0, text: 'help'},
{id: 0, text: 'high five'},
{id: 0, text: 'hug'},
{id: 0, text: 'idgaf'},
{id: 0, text: 'idk'},
{id: 0, text: 'kiss'},
{id: 0, text: 'lol'},
{id: 0, text: 'meh'},
{id: 0, text: 'mic drop'},
{id: 0, text: 'middle finger'},
{id: 0, text: 'no'},
{id: 0, text: 'oh no you didnt'},
{id: 0, text: 'oh snap'},
{id: 0, text: 'ok'},
{id: 0, text: 'omg'},
{id: 0, text: 'oops'},
{id: 0, text: 'please'},
{id: 0, text: 'popcorn'},
{id: 0, text: 'seriously'},
{id: 0, text: 'shrug'},
{id: 0, text: 'shut up'},
{id: 0, text: 'sigh'},
{id: 0, text: 'slow clap'},
{id: 0, text: 'smh'},
{id: 0, text: 'smile'},
{id: 0, text: 'sorry'},
{id: 0, text: 'squee'},
{id: 0, text: 'suck it'},
{id: 0, text: 'table flip'},
{id: 0, text: 'thank you'},
{id: 0, text: 'thumbs down'},
{id: 0, text: 'thumbs up'},
{id: 0, text: 'ugh'},
{id: 0, text: 'want'},
{id: 0, text: 'what'},
{id: 0, text: 'whatever'},
{id: 0, text: 'win'},
{id: 0, text: 'wink'},
{id: 0, text: 'wow'},
{id: 0, text: 'wtf'},
{id: 0, text: 'yawn'},
{id: 0, text: 'yes'},
{id: 0, text: 'yolo'},
{id: 0, text: 'you got this'},

// Science
{id: 0, text: 'asteroids'},
{id: 0, text: 'astronomy'},
{id: 0, text: 'atoms'},
{id: 0, text: 'bill nye'},
{id: 0, text: 'biology'},
{id: 0, text: 'bubbles'},
{id: 0, text: 'chemistry'},
{id: 0, text: 'computers'},
{id: 0, text: 'diy'},
{id: 0, text: 'engineering'},
{id: 0, text: 'global warming'},
{id: 0, text: 'laser'},
{id: 0, text: 'magnets'},
{id: 0, text: 'mathematics'},
{id: 0, text: 'medicine'},
{id: 0, text: 'meteor'},
{id: 0, text: 'molecules'},
{id: 0, text: 'nebula'},
{id: 0, text: 'nuclear'},
{id: 0, text: 'physics'},
{id: 0, text: 'planets'},
{id: 0, text: 'robot'},
{id: 0, text: 'space'},
{id: 0, text: 'stars'},
{id: 0, text: 'technology'},
{id: 0, text: 'nasa'},

// Sports
{id: 0, text: 'archery'},
{id: 0, text: 'base jumping'},
{id: 0, text: 'baseball'},
{id: 0, text: 'basketball'},
{id: 0, text: 'bowling'},
{id: 0, text: 'boxing'},
{id: 0, text: 'diving'},
{id: 0, text: 'football'},
{id: 0, text: 'formula one'},
{id: 0, text: 'golf'},
{id: 0, text: 'gymnastics'},
{id: 0, text: 'hockey'},
{id: 0, text: 'horse racing'},
{id: 0, text: 'lacrosse'},
{id: 0, text: 'martial arts'},
{id: 0, text: 'mma'},
{id: 0, text: 'nascar'},
{id: 0, text: 'parkour'},
{id: 0, text: 'rock climbing'},
{id: 0, text: 'roller skating'},
{id: 0, text: 'rowing'},
{id: 0, text: 'rugby'},
{id: 0, text: 'skateboarding'},
{id: 0, text: 'skiing'},
{id: 0, text: 'skydiving'},
{id: 0, text: 'snowboarding'},
{id: 0, text: 'soccer'},
{id: 0, text: 'softball'},
{id: 0, text: 'surfing'},
{id: 0, text: 'swimming'},
{id: 0, text: 'tennis'},
{id: 0, text: 'volleyball'},
{id: 0, text: 'wrestling'},
{id: 0, text: 'nfl'},


// Transportation (possibly super lame)
{id: 0, text: 'airplane'},
{id: 0, text: 'audi'},
{id: 0, text: 'bicycle'},
{id: 0, text: 'bmw'},
{id: 0, text: 'boat'},
{id: 0, text: 'bus'},
{id: 0, text: 'car'},
{id: 0, text: 'chevrolet'},
{id: 0, text: 'ferrari'},
{id: 0, text: 'helicopter'},
{id: 0, text: 'honda'},
{id: 0, text: 'hovercraft'},
{id: 0, text: 'motorcycle'},
{id: 0, text: 'nissan'},
{id: 0, text: 'porsche'},
{id: 0, text: 'rocket'},
{id: 0, text: 'sailboat'},
{id: 0, text: 'spaceship'},
{id: 0, text: 'submarine'},
{id: 0, text: 'tank'},
{id: 0, text: 'tesla'},
{id: 0, text: 'toyota'},
{id: 0, text: 'train'},
{id: 0, text: 'truck'},
{id: 0, text: 'van'},
{id: 0, text: 'volkswagen'},
{id: 0, text: 'yacht'},

// Tv
{id: 0, text: 'rick and morty'},
{id: 0, text: '30 rock'},
{id: 0, text: 'alfred hitchcock presents'},
{id: 0, text: 'american idol'},
{id: 0, text: 'are you afraid of the dark?'},
{id: 0, text: 'arrested development'},
{id: 0, text: 'battlestar galactica'},
{id: 0, text: 'baywatch'},
{id: 0, text: 'boardwalk empire'},
{id: 0, text: 'bones'},
{id: 0, text: 'bored to death'},
{id: 0, text: 'boy meets world'},
{id: 0, text: 'breaking bad'},
{id: 0, text: 'californication'},
{id: 0, text: 'castle'},
{id: 0, text: 'cbs'},
{id: 0, text: 'charles in charge'},
{id: 0, text: 'cheers'},
{id: 0, text: 'chuck'},
{id: 0, text: 'clarissa explains it all'},
{id: 0, text: 'comedy central'},
{id: 0, text: 'criminal minds'},
{id: 0, text: 'csi'},
{id: 0, text: 'csi miami'},
{id: 0, text: 'curb your enthusiasm'},
{id: 0, text: 'damages'},
{id: 0, text: 'degrassi'},
{id: 0, text: 'desperate housewives'},
{id: 0, text: 'dexter'},
{id: 0, text: 'doctor who'},
{id: 0, text: 'downton abbey'},
{id: 0, text: 'eastbound and down'},
{id: 0, text: 'elementary'},
{id: 0, text: 'entourage'},
{id: 0, text: 'even stevens'},
{id: 0, text: 'family ties'},
{id: 0, text: 'flavor of love'},
{id: 0, text: 'freaks and geeks'},
{id: 0, text: 'friday night lights'},
{id: 0, text: 'fringe'},
{id: 0, text: 'full house'},
{id: 0, text: 'fx'},
{id: 0, text: 'game of thrones'},
{id: 0, text: 'glee'},
{id: 0, text: 'gossip girl'},
{id: 0, text: 'greys anatomy'},
{id: 0, text: 'happy days'},
{id: 0, text: 'hawaii five o'},
{id: 0, text: 'hbo'},
{id: 0, text: 'hells kitchen'},
{id: 0, text: 'heroes'},
{id: 0, text: 'house'},
{id: 0, text: 'human giant'},
{id: 0, text: 'human target'},
{id: 0, text: 'hung'},
{id: 0, text: 'i love lucy'},
{id: 0, text: 'in treatment'},
{id: 0, text: 'its always sunny in philadelphia'},
{id: 0, text: 'jag'},
{id: 0, text: 'key and peele'},
{id: 0, text: 'kitchen nightmares'},
{id: 0, text: 'knight rider'},
{id: 0, text: 'lie to me'},
{id: 0, text: 'lost'},
{id: 0, text: 'macgyver'},
{id: 0, text: 'mad men'},
{id: 0, text: 'magnum pi'},
{id: 0, text: 'married with children'},
{id: 0, text: 'mash'},
{id: 0, text: 'miami vice'},
{id: 0, text: 'mildred pierce'},
{id: 0, text: 'misfits'},
{id: 0, text: 'modern family'},
{id: 0, text: 'monk'},
{id: 0, text: 'mr ed'},
{id: 0, text: 'muppets'},
{id: 0, text: 'nbc'},
{id: 0, text: 'ncis'},
{id: 0, text: 'new girl'},
{id: 0, text: 'nickelodeon'},
{id: 0, text: 'nikita'},
{id: 0, text: 'one tree hill'},
{id: 0, text: 'parks and recreation'},
{id: 0, text: 'party down'},
{id: 0, text: 'pete and pete'},
{id: 0, text: 'portlandia'},
{id: 0, text: 'pretty little liars'},
{id: 0, text: 'prison break'},
{id: 0, text: 'private practice'},
{id: 0, text: 'quantum leap'},
{id: 0, text: 'raising hope'},
{id: 0, text: 'reno 911'},
{id: 0, text: 'ron swanson'},
{id: 0, text: 'salute your shorts'},
{id: 0, text: 'saved by the bell'},
{id: 0, text: 'scrubs'},
{id: 0, text: 'seinfeld'},
{id: 0, text: 'sesame street'},
{id: 0, text: 'sherlock'},
{id: 0, text: 'showtime'},
{id: 0, text: 'six feet under'},
{id: 0, text: 'smallville'},
{id: 0, text: 'sons of anarchy'},
{id: 0, text: 'star trek'},
{id: 0, text: 'starsky and hutch'},
{id: 0, text: 'supernatural'},
{id: 0, text: 'tales from the crypt'},
{id: 0, text: 'the a team'},
{id: 0, text: 'the biggest loser'},
{id: 0, text: 'the cosby show'},
{id: 0, text: 'the good wife'},
{id: 0, text: 'the killing'},
{id: 0, text: 'the mentalist'},
{id: 0, text: 'the muppet show'},
{id: 0, text: 'the oc'},
{id: 0, text: 'the office'},
{id: 0, text: 'the outs'},
{id: 0, text: 'the ricky gervais show'},
{id: 0, text: 'the sopranos'},
{id: 0, text: 'the state'},
{id: 0, text: 'the walking dead'},
{id: 0, text: 'the west wing'},
{id: 0, text: 'the wire'},
{id: 0, text: 'third rock from the sun'},
{id: 0, text: 'threes company'},
{id: 0, text: 'tmc'},
{id: 0, text: 'top chef'},
{id: 0, text: 'top gear'},
{id: 0, text: 'treme'},
{id: 0, text: 'true blood'},
{id: 0, text: 'twenty four'},
{id: 0, text: 'twin peaks'},
{id: 0, text: 'undeclared'},
{id: 0, text: 'veronica mars'},
{id: 0, text: 'webster'},
{id: 0, text: 'weeds'},
{id: 0, text: 'workaholics'},
]


// Loop for seeding answerObject
for (let i = 0; i < answerObject.length; i++) {
	let searchTerm = new Answer({
		id: i+1,
		text: answerObject[i].text
	});
	searchTerm.save((error) => {
		if (error) {
			console.log(error);
		};
	});
};











//
